#
# tinyflex: A minimal, dependency-free, single-header library, FLEX encoder.
# Written by Davidson Francis (aka Theldus) - 2025.
#
# This is free and unencumbered software released into the public domain.
#

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    name: Build demos
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build demos
      run:  cd demos && make
    - name: Check for correctness
      run: |
        cd demos
        hash1=$(printf "1234567:HACK THE PLANET" | ./encode_file | md5sum | awk '{print $1}')
        hash2=$(md5sum ../tests/reference_output.bin | awk '{print $1}')
        if [ "$hash1" = "$hash2" ]; then
          echo "OK"
        else
          echo "FAIL"
          exit 1
        fi
